const data = [
  {
    id: 1,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "Novel",
    price: 850,
    available: 25,
    client: "Donald Trump 3",
    address: "221 B Baker Street...",
    phone: "+88-01812-345678",
    status: "placed",
  },
  {
    id: 2,
    name: "The art of self defense...",
    author: "MKBHD 2",
    category: "Novel",
    price: 850,
    available: 25,
    client: "Donald Trump 3",
    address: "221 B Baker Street...",
    phone: "+88-01812-345678",
    status: "confirm",
  },
  {
    id: 3,
    name: "The art of self ",
    author: "ABCD",
    category: "Novel",
    price: 850,
    available: 25,
    client: "Donald Trump1",
    address: "221 B Baker Street...",
    phone: "+88-01812-345678",
    status: "processing",
  },
  {
    id: 4,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "Novel",
    price: 850,
    available: 25,
    client: "Donald Trump 6",
    address: "221 B Baker Street...",
    phone: "+88-01812-345678",
    status: "shipped",
  },
  {
    id: 5,
    name: "The art of self 9",
    author: "MKBHD",
    category: "Novel",
    price: 850,
    available: 25,
    client: "Donald Trump",
    address: "221 B Baker Street...",
    phone: "+88-01812-345678",
    status: "pending",
  },
];

export default data;
