export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
export const LOAD_ADMIN_DATA = "LOAD_ADMIN_DATA";
export const LOAD_ADMIN_USERS = "LOAD_ADMIN_USERS";
export const LOAD_ADMIN_ORDERS = "LOAD_ADMIN_ORDERS";
export const ADMIN_REMOVE = "ADMIN_REMOVE";

//BOOK
export const GET_BOOK = "GET_BOOK";
export const CREATE_BOOK = "CREATE_BOOK";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const BOOK_ERROR = "BOOK_ERROR";

//AUTHOR
export const GET_AUTHOR = "GET_AUTHOR";
export const CREATE_AUTHOR = "CREATE_AUTHOR";
export const UPDATE_AUTHOR = "UPDATE_AUTHOR";
export const DELETE_AUTHOR = "DELETE_AUTHOR";
export const AUTHOR_ERROR = "AUTHOR_ERROR";
export const ADD_AUTHOR_MODAL_TOGGLE = "ADD_AUTHOR_MODAL_TOGGLE";

//REQUESTED BOOK
export const GET_REQUESTED_BOOK = "GET_REQUESTED_BOOK";
export const DELETE_REQUESTED_BOOK = "DELETE_REQUESTED_BOOK";
export const REQUESTED_BOOK_ERROR = "REQUESTED_BOOK_ERROR";

//BLOG
export const GET_BLOG = "GET_BLOG";
export const CREATE_BLOG = "CREATE_BLOG";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";
export const BLOG_ERROR = "BLOG_ERROR";
export const BLOG_EDIT_MODAL = "BLOG_EDIT_MODAL";

//ORDER
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const ORDER_ERROR = "ORDER_ERROR";

//ERRORS AND ADD AND REMOVE
export const BEST_SELLER_ERROR = "BEST_SELLER_ERROR";
export const BEST_SELLER_ADD = "BEST_SELLER_ADD";
export const BEST_SELLER_REMOVE = "BEST_SELLER_REMOVE";
export const TRENDING_ADD = "TRENDING_ADD";
export const TRENDING_REMOVE = "TRENDING_REMOVE";
export const TRENDING_ERROR = "TRENDING_ERROR";
export const NEW_ARRIVALS_ERROR = "NEW_ARRIVALS_ERROR";
export const NEW_ARRIVALS_ADD = "NEW_ARRIVALS_ADD";
export const NEW_ARRIVALS_REMOVE = "NEW_ARRIVALS_REMOVE";
export const ON_SALE_ERROR = "ON_SALE_ERROR";
export const ON_SALE_ADD = "ON_SALE_ADD";
export const ON_SALE_REMOVE = "ON_SALE_REMOVE";
export const PRE_ORDER_ERROR = "PRE_ORDER_ERROR";
export const PRE_ORDER_ADD = "PRE_ORDER_ADD";
export const PRE_ORDER_REMOVE = "PRE_ORDER_REMOVE";
export const GET_HERO_CAROUSELS = "GET_HERO_CAROUSELS";
export const HERO_CAROUSEL_ADD = "HERO_CAROUSEL_ADD";
export const HERO_CAROUSEL_REMOVE = "HERO_CAROUSEL_REMOVE";
export const HERO_CAROUSEL_ERROR = "HERO_CAROUSEL_ERROR";
export const HERO_CAROUSEL_UPDATE = "HERO_CAROUSEL_UPDATE";

export const GET_ADS = "GET_ADS";
export const GET_ADS_FRONT = "GET_ADS_FRONT";
export const AD_ADD = "AD_ADD";
export const AD_REMOVE = "AD_REMOVE";
export const AD_ERROR = "AD_ERROR";
export const AD_UPDATE = "AD_UPDATE";

export const GET_CATEGORY = "GET_CATEGORY";
export const CATEGORY_ADD = "CATEGORY_ADD";
export const CATEGORY_REMOVE = "CATEGORY_REMOVE";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const CATEGORY_UPDATE = "CATEGORY_UPDATE";
export const ADD_CATEGORY_MODAL_TOGGLE = "ADD_CATEGORY_MODAL_TOGGLE";
export const EDIT_CATEGORY_MODAL_TOGGLE = "EDIT_CATEGORY_MODAL_TOGGLE";

export const GET_CUPON = "GET_CUPON";
export const CUPON_ADD = "CUPON_ADD";
export const CUPON_REMOVE = "CUPON_REMOVE";
export const CUPON_ERROR = "CUPON_ERROR";
export const CUPON_UPDATE = "CUPON_UPDATE";
export const ADD_CUPON_MODAL_TOGGLE = "ADD_CUPON_MODAL_TOGGLE";
export const EDIT_CUPON_MODAL_TOGGLE = "EDIT_CUPON_MODAL_TOGGLE";

export const GET_PUBLISHER = "GET_PUBLISHER";
export const PUBLISHER_ADD = "PUBLISHER_ADD";
export const PUBLISHER_REMOVE = "PUBLISHER_REMOVE";
export const PUBLISHER_ERROR = "PUBLISHER_ERROR";
export const PUBLISHER_UPDATE = "PUBLISHER_UPDATE";
export const ADD_PUBLISHER_MODAL_TOGGLE = "ADD_PUBLISHER_MODAL_TOGGLE";
export const EDIT_PUBLISHER_MODAL_TOGGLE = "EDIT_PUBLISHER_MODAL_TOGGLE";

//ADMIN LIST
export const GET_ADMIN = "GET_ADMIN";
export const CREATE_ADMIN = "CREATE_ADMIN";
export const ADMIN_ERROR = "ADMIN_ERROR";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const EDIT_ADMIN = "EDIT_ADMIN";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_ORDER_ITEM = "GET_ORDER_ITEM";

export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";
export const BLOG_MODAL_TOGGLE = "BLOG_MODAL_TOGGLE";

export const BEST_SELLER_MODAL_TOGGLE = "BEST_SELLER_MODAL_TOGGLE";
export const TRENDING_MODAL_TOGGLE = "TRENDING_MODAL_TOGGLE";
export const NEW_ARRIVALS_MODAL_TOGGLE = "NEW_ARRIVALS_MODAL_TOGGLE";
export const ON_SALE_MODAL_TOGGLE = "ON_SALE_MODAL_TOGGLE";
export const PRE_ORDER_MODAL_TOGGLE = "PRE_ORDER_MODAL_TOGGLE";
export const HERO_CAROUSEL_MODAL_TOGGLE = "HERO_CAROUSEL_MODAL_TOGGLE";
export const AD_MODAL_TOGGLE = "AD_MODAL_TOGGLE";

// /////////////////////////////////////
// =============== VIEWER =============
// Book related
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const UPDATE_WISHLIST = "UPDATE_WISHLIST";
export const SAVE_BOOKS = "SAVE_BOOKS";
export const FILTER_CATEGORIES = "FILTER_CATEGORIES";
export const FILTER_BOOKS = "FILTER_BOOKS";

// Auth related
export const LOGIN_SIGNUP_MODAL = "LOGIN_SIGNUP_MODAL";
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";
export const ADMIN_USER_DELETED = "ADMIN_USER_DELETED";
export const ADMIN_USER_DELETED_ERROR = "ADMIN_USER_DELETED_ERROR";
