export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_BOOK = "GET_BOOK";
export const GET_ORDER_ITEM = "GET_ORDER_ITEM";

export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";
export const BLOG_MODAL_TOGGLE = "BLOG_MODAL_TOGGLE";
export const BEST_SELLER_MODAL_TOGGLE = "BEST_SELLER_MODAL_TOGGLE";
export const TRENDING_MODAL_TOGGLE = "TRENDING_MODAL_TOGGLE";
export const NEW_ARRIVALS_MODAL_TOGGLE = "NEW_ARRIVALS_MODAL_TOGGLE";
export const ON_SALE_MODAL_TOGGLE = "ON_SALE_MODAL_TOGGLE";
export const PRE_ORDER_MODAL_TOGGLE = "PRE_ORDER_MODAL_TOGGLE";
export const HERO_CAROUSEL_MODAL_TOGGLE = "HERO_CAROUSEL_MODAL_TOGGLE";

//VIEWER
export const LOGIN_SIGNUP_MODAL = "LOGIN_SIGNUP_MODAL";
