const data = [
  {
    id: 1,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "থ্রিলার",
    price: 850,
    available: 25,
  },
  {
    id: 15,
    name: "The art of self defense...",
    author: "MKBHD 2",
    category: "চিরায়ত উপন্যাস",
    price: 850,
    available: 25,
  },
  {
    id: 14,
    name: "The art of self ",
    author: "ABCD",
    category: "থ্রিলার",
    price: 850,
    available: 25,
  },
  {
    id: 2,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "কম্পিউটার ও প্রোগ্রামিং",
    price: 850,
    available: 25,
  },
  {
    id: 3,
    name: "The art of self 9",
    author: "MKBHD",
    category: "সিরিজ",
    price: 850,
    available: 25,
  },
  {
    id: 4,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "অনুবাদ বই",
    price: 850,
    available: 25,
  },
  {
    id: 5,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "কম্পিউটার ও প্রোগ্রামিং",
    price: 850,
    available: 25,
  },
  {
    id: 6,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "কম্পিউটার ও প্রোগ্রামিং",
    price: 850,
    available: 25,
  },
  {
    id: 7,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "কম্পিউটার ও প্রোগ্রামিং",
    price: 850,
    available: 25,
  },
  {
    id: 8,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "কম্পিউটার ও প্রোগ্রামিং",
    price: 850,
    available: 25,
  },
  {
    id: 9,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "কম্পিউটার ও প্রোগ্রামিং",
    price: 850,
    available: 25,
  },
  {
    id: 11,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "কম্পিউটার ও প্রোগ্রামিং",
    price: 850,
    available: 25,
  },
  {
    id: 12,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "কম্পিউটার ও প্রোগ্রামিং",
    price: 850,
    available: 25,
  },
  {
    id: 13,
    name: "The art of self defense...",
    author: "MKBHD",
    category: "কম্পিউটার ও প্রোগ্রামিং",
    price: 850,
    available: 25,
  },
];

export default data;
